// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyrCLW4KKQE-UiXfslf146UrQcESFInC0',
    appId: '1:679860055501:web:a5dec5df831f0feebfe884',
    messagingSenderId: '679860055501',
    projectId: 'rntspots-65a06',
    authDomain: 'rntspots-65a06.firebaseapp.com',
    storageBucket: 'rntspots-65a06.appspot.com',
    measurementId: 'G-XZJ5WX20V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi5xNFlFZLYmF_j3Zu6o1-aMbg43u5-fw',
    appId: '1:679860055501:android:eb49bd952ce4875fbfe884',
    messagingSenderId: '679860055501',
    projectId: 'rntspots-65a06',
    storageBucket: 'rntspots-65a06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd-XeQABbjyxDFJchHNEeNkUhvi2m4440',
    appId: '1:679860055501:ios:cfcc3628850c942ebfe884',
    messagingSenderId: '679860055501',
    projectId: 'rntspots-65a06',
    storageBucket: 'rntspots-65a06.appspot.com',
    iosBundleId: 'com.example.rntSpots',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd-XeQABbjyxDFJchHNEeNkUhvi2m4440',
    appId: '1:679860055501:ios:756a83037252453cbfe884',
    messagingSenderId: '679860055501',
    projectId: 'rntspots-65a06',
    storageBucket: 'rntspots-65a06.appspot.com',
    iosBundleId: 'com.example.rntSpots.RunnerTests',
  );
}
